[package]
name = "sqlite-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
cryptbox = { version = "=0.5.0", features = ["sqlx-sqlite"] }
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite"] }
futures-executor = "0.3.34"
