use crate::Error;

mod encoding;
mod part;

pub use part::PartType;

/// The type of the record ID a seal binds its values to, or `()` for a seal
/// that binds no record.
///
/// It is [`Seal::Record`](crate::Seal::Record). Every [`PartType`] is one: a
/// seal whose `Record` is `i64` binds every value to the `i64` ID of the row it
/// is stored in, so a value copied to another row fails to open. The record ID's
/// kind is part of the binding declaration: changing it is a migration. Record
/// IDs are generated by the client, such as version 7 UUIDs, before the value is
/// sealed, and are never reused. A record never takes part in a blind index,
/// since a query cannot know it.
pub trait RecordIdType: 'static {
    /// The kind of the record ID, or `None` without a record.
    const RECORD: Option<PartKind>;
}

impl RecordIdType for () {
    const RECORD: Option<PartKind> = None;
}

impl<T: PartType + 'static> RecordIdType for T {
    const RECORD: Option<PartKind> = Some(T::KIND);
}

/// The binding fingerprint of a seal that binds record `R`, as the envelope
/// header carries it.
pub(crate) fn declaration_fingerprint<R: RecordIdType>() -> [u8; 8] {
    BindingDeclaration::new(R::RECORD).fingerprint()
}

/// The canonical kind of a record ID.
///
/// Kinds are fixed: there is no text kind. Encode text as bytes.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PartKind {
    /// A 16-byte UUID.
    Uuid,
    /// A signed 64-bit integer.
    I64,
    /// Opaque bytes.
    Bytes,
}

/// The value of a record ID, as it is bound.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PartValue<'a> {
    /// A 16-byte UUID.
    Uuid([u8; 16]),
    /// A signed 64-bit integer.
    I64(i64),
    /// Opaque bytes.
    Bytes(&'a [u8]),
}

impl PartValue<'_> {
    pub(crate) fn kind(&self) -> PartKind {
        match self {
            Self::Uuid(_) => PartKind::Uuid,
            Self::I64(_) => PartKind::I64,
            Self::Bytes(_) => PartKind::Bytes,
        }
    }
}

/// The ID of the record a value is bound to, tagged with its kind.
///
/// The kind is part of the binding, so the same number as an `i64` and as bytes
/// binds different records.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum RecordId<'a> {
    /// A UUID, such as a client-generated version 7 UUID.
    Uuid([u8; 16]),
    /// A signed 64-bit integer.
    I64(i64),
    /// Opaque bytes.
    Bytes(&'a [u8]),
}

impl<'a> RecordId<'a> {
    /// Creates a record ID from opaque bytes.
    #[must_use]
    pub const fn from_bytes(bytes: &'a [u8]) -> Self {
        Self::Bytes(bytes)
    }

    /// Creates a record ID from any [`PartType`], such as an application's own
    /// ID newtype, with that type's kind and value.
    #[must_use]
    pub fn of<T: PartType + ?Sized>(id: &'a T) -> Self {
        match id.part_value() {
            PartValue::Uuid(uuid) => Self::Uuid(uuid),
            PartValue::I64(value) => Self::I64(value),
            PartValue::Bytes(bytes) => Self::Bytes(bytes),
        }
    }
}

impl From<[u8; 16]> for RecordId<'_> {
    fn from(uuid: [u8; 16]) -> Self {
        Self::Uuid(uuid)
    }
}

#[cfg(feature = "uuid")]
impl From<uuid::Uuid> for RecordId<'_> {
    fn from(uuid: uuid::Uuid) -> Self {
        Self::Uuid(*uuid.as_bytes())
    }
}

impl From<i64> for RecordId<'_> {
    fn from(value: i64) -> Self {
        Self::I64(value)
    }
}

#[cfg(feature = "migrate")]
impl<'a> RecordId<'a> {
    // Records share the part value encoding, kind codes included.
    pub(crate) const fn part_value(self) -> PartValue<'a> {
        match self {
            Self::Uuid(uuid) => PartValue::Uuid(uuid),
            Self::I64(value) => PartValue::I64(value),
            Self::Bytes(bytes) => PartValue::Bytes(bytes),
        }
    }
}

/// One part of a binding's encoding: an ID and a value kind.
///
/// A record is bound as the one part, under the nil part ID. See
/// ../docs/wire-format.md#binding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct PartSpec {
    id: [u8; 16],
    kind: PartKind,
}

impl PartSpec {
    const fn record(kind: PartKind) -> Self {
        Self { id: [0; 16], kind }
    }
}

/// The persistent declaration of a binding: the record's kind, when it binds
/// one.
#[derive(Clone, Copy, Debug)]
pub(crate) struct BindingDeclaration {
    record: Option<PartKind>,
}

impl BindingDeclaration {
    pub(crate) const fn new(record: Option<PartKind>) -> Self {
        Self { record }
    }

    /// Every part of the declaration: the record's, if it binds one.
    fn specs(self) -> Vec<PartSpec> {
        self.record.map(PartSpec::record).into_iter().collect()
    }

    /// Fingerprints the declaration.
    pub(crate) fn fingerprint(self) -> [u8; 8] {
        encoding::fingerprint(&self.specs())
    }
}

/// A binding resolved for the cryptographic core, or a blind index's.
///
/// The encoded bytes are the domain separator that encryption mixes into key
/// derivation and AAD, and that a blind index mixes into its MAC input. The
/// binding fingerprint is recorded in the envelope and checked by readers. The
/// domain starts with the 16 bytes of an identity, a seal ID, which it does not
/// interpret; choosing keys is the typed layer's.
#[derive(Clone, Debug)]
pub(crate) struct BindingDomain {
    encoded: Vec<u8>,
    fingerprint: [u8; 8],
}

impl BindingDomain {
    /// Encodes the binding of seal `id` under `declaration`, with its record's
    /// value if the declaration binds one.
    ///
    /// A record the declaration does not bind, a missing record, and a record
    /// of another kind are [`Error::InvalidBinding`].
    pub(crate) fn new(
        id: &[u8; 16],
        declaration: BindingDeclaration,
        record: Option<PartValue<'_>>,
    ) -> Result<Self, Error> {
        let record = match (declaration.record, record) {
            (Some(kind), Some(record)) if record.kind() == kind => {
                Some((PartSpec::record(kind), record))
            }
            (None, None) => None,
            _ => return Err(Error::InvalidBinding),
        };

        Ok(Self {
            encoded: encoding::encode(id, record.iter().map(|(spec, value)| (spec, value)))?,
            fingerprint: declaration.fingerprint(),
        })
    }

    /// Encodes the binding of seal `id`, which binds record `R`, with the
    /// record's value if `R` is one.
    pub(crate) fn record<R: RecordIdType>(
        id: &[u8; 16],
        record: Option<PartValue<'_>>,
    ) -> Result<Self, Error> {
        Self::new(id, BindingDeclaration::new(R::RECORD), record)
    }

    /// Encodes the blind-index domain of seal `id`: the seal ID alone, the
    /// empty binding, since a query cannot know a record.
    // See ../docs/wire-format.md#index-binding.
    pub(crate) fn index(id: &[u8; 16]) -> Self {
        Self {
            encoded: encoding::encode(id, std::iter::empty())
                .expect("the empty binding always encodes"),
            fingerprint: BindingDeclaration::new(None).fingerprint(),
        }
    }

    /// The binding fingerprint the envelope header carries.
    pub(crate) fn fingerprint(&self) -> [u8; 8] {
        self.fingerprint
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.encoded
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::seal_id;

    const SEAL: [u8; 16] = *seal_id!("12345678-1234-4234-8234-1234567890ab").as_bytes();

    fn domain(
        record: Option<PartKind>,
        value: Option<PartValue<'_>>,
    ) -> Result<BindingDomain, Error> {
        BindingDomain::new(&SEAL, BindingDeclaration::new(record), value)
    }

    fn hex_array(value: &str) -> [u8; 8] {
        hex::decode(value).unwrap().try_into().unwrap()
    }

    #[test]
    fn the_empty_binding_is_the_seal_id_without_parts() {
        let domain = domain(None, None).unwrap();

        // docs/wire-format.md#binding
        assert_eq!(
            hex::encode(domain.as_bytes()),
            "123456781234423482341234567890ab0000"
        );
        // Independently computed with shasum over the documented empty declaration.
        assert_eq!(domain.fingerprint(), hex_array("65640fc8333534b9"));
        assert_eq!(BindingDomain::index(&SEAL).as_bytes(), domain.as_bytes());
    }

    #[test]
    fn a_record_is_one_part_under_the_nil_id() {
        let domain = domain(Some(PartKind::I64), Some(PartValue::I64(1))).unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            concat!(
                "123456781234423482341234567890ab",
                "0001",
                "00000000000000000000000000000000",
                "02",
                "00000008",
                "0000000000000001",
            )
        );
        // Independently computed with shasum over the documented declaration bytes.
        assert_eq!(domain.fingerprint(), hex_array("76081b730530f822"));
    }

    #[test]
    fn a_bytes_record_is_length_prefixed() {
        let domain = domain(Some(PartKind::Bytes), Some(PartValue::Bytes(b"row-7"))).unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            concat!(
                "123456781234423482341234567890ab",
                "0001",
                "00000000000000000000000000000000",
                "03",
                "00000005",
                "726f772d37",
            )
        );
    }

    #[test]
    fn records_of_different_kinds_never_collide() {
        let bytes = domain(
            Some(PartKind::Bytes),
            Some(PartValue::Bytes(&7_i64.to_be_bytes())),
        );
        let number = domain(Some(PartKind::I64), Some(PartValue::I64(7)));

        assert_ne!(bytes.unwrap().as_bytes(), number.unwrap().as_bytes());
        // The record's kind is declared.
        assert_ne!(
            BindingDeclaration::new(Some(PartKind::I64)).fingerprint(),
            BindingDeclaration::new(Some(PartKind::Bytes)).fingerprint(),
        );
    }

    #[test]
    fn an_empty_record_differs_from_no_record() {
        assert_ne!(
            domain(None, None).unwrap().as_bytes(),
            domain(Some(PartKind::Bytes), Some(PartValue::Bytes(b"")))
                .unwrap()
                .as_bytes(),
        );
    }

    #[test]
    fn invalid_records_are_rejected() {
        let uuid = PartValue::Uuid([0x33; 16]);
        let cases = [
            ("missing record", domain(Some(PartKind::Uuid), None)),
            (
                "record of another kind",
                domain(Some(PartKind::I64), Some(uuid)),
            ),
            ("unexpected record", domain(None, Some(uuid))),
        ];

        for (case, result) in cases {
            assert_eq!(result.unwrap_err(), Error::InvalidBinding, "{case}");
        }
    }
}
