use crate::Error;
use crate::id::identifier;

mod bound_id;
mod encoding;
mod part;
mod presets;

pub(crate) use bound_id::OwnedBinding;
pub(crate) use bound_id::bound_values;
#[cfg(feature = "restate")]
pub(crate) use bound_id::from_part_values;
pub use bound_id::{BoundId, BoundList, BoundValues};
pub use part::PartType;
pub use presets::TenantId;

identifier!(
    PartId,
    "A stable binding-part identifier, independent of Rust names."
);

/// The type of the record ID a seal binds its values to, or `()` for a seal
/// that binds no record.
///
/// It is [`Seal::Record`](crate::Seal::Record). Every [`PartType`] is one: a
/// seal whose `Record` is `i64` binds every value to the `i64` ID of the row it
/// is stored in, so a value copied to another row fails to open. The record is
/// bound as one more part, under the nil part ID, with the ID type's kind: a
/// declaration change when it changes. Record IDs are generated by the client,
/// such as version 7 UUIDs, before the value is sealed, and are never reused. A
/// record never partitions a blind index, since a query cannot know it.
pub trait RecordIdType: 'static {
    /// The kind of the record ID, or `None` without a record.
    const RECORD: Option<PartKind>;
}

impl RecordIdType for () {
    const RECORD: Option<PartKind> = None;
}

impl<T: PartType + 'static> RecordIdType for T {
    const RECORD: Option<PartKind> = Some(T::KIND);
}

// Whether every part of `view` is a part of `parts`, with the same ID and kind.
const fn is_view(view: &[PartSpec], parts: &[PartSpec]) -> bool {
    let mut index = 0;
    while index < view.len() {
        let mut found = false;
        let mut candidate = 0;
        while candidate < parts.len() {
            if u128::from_be_bytes(view[index].id) == u128::from_be_bytes(parts[candidate].id)
                && view[index].kind as u8 == parts[candidate].kind as u8
            {
                found = true;
            }
            candidate += 1;
        }
        if !found {
            return false;
        }
        index += 1;
    }

    true
}

// Panics become build errors in `const` context.
pub(crate) const fn check_partition(partition: &[PartSpec], bound: &[PartSpec]) {
    assert!(
        is_view(partition, bound),
        "a blind index is partitioned by bound values its seal binds: each of its \
         partition's types must be one of the seal's bound types"
    );
}

/// Checks that `values` holds exactly one value per spec, in order, of the
/// spec's kind.
pub(crate) fn check_values<'s>(
    specs: impl IntoIterator<Item = &'s PartSpec>,
    values: &[PartValue<'_>],
) -> Result<(), Error> {
    let mut values = values.iter();
    for spec in specs {
        let value = values.next().ok_or(Error::InvalidBinding)?;
        if spec.kind != value.kind() {
            return Err(Error::InvalidBinding);
        }
    }

    match values.next() {
        Some(_) => Err(Error::InvalidBinding),
        None => Ok(()),
    }
}

/// Takes the value of each of `specs` from `parts`, by part ID; a missing part
/// or another kind is [`Error::InvalidBinding`].
pub(crate) fn project<'v>(
    specs: &[PartSpec],
    parts: &[PartSpec],
    values: &[PartValue<'v>],
) -> Result<Vec<PartValue<'v>>, Error> {
    check_values(parts, values)?;

    specs
        .iter()
        .map(|spec| {
            parts
                .iter()
                .zip(values)
                .find(|(part, _)| part.id == spec.id && part.kind == spec.kind)
                .map(|(_, value)| *value)
                .ok_or(Error::InvalidBinding)
        })
        .collect()
}

/// The binding fingerprint of a seal that binds `L` and record `R`, as the
/// envelope header carries it.
pub(crate) fn declaration_fingerprint<L: BoundList, R: RecordIdType>() -> [u8; 8] {
    BindingDeclaration::new(L::PARTS, R::RECORD).fingerprint()
}

/// The canonical kind of a part or record value.
///
/// Kinds are fixed: there is no text kind. Encode text as bytes.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PartKind {
    /// A 16-byte UUID.
    Uuid,
    /// A signed 64-bit integer.
    I64,
    /// Opaque bytes.
    Bytes,
}

/// One declared part of a binding: its ID and value kind, such as a
/// [`BoundId`]'s [`PART`](BoundId::PART).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PartSpec {
    id: [u8; 16],
    kind: PartKind,
}

impl PartSpec {
    /// Declares a part with ID `id` and values of kind `kind`.
    #[must_use]
    pub const fn new(id: PartId, kind: PartKind) -> Self {
        Self::from_bytes(*id.as_bytes(), kind)
    }

    pub(crate) const fn from_bytes(id: [u8; 16], kind: PartKind) -> Self {
        Self { id, kind }
    }

    /// Returns the part ID.
    #[must_use]
    pub const fn id(&self) -> PartId {
        PartId::from_bytes(self.id)
    }

    /// Returns the value kind.
    #[must_use]
    pub const fn kind(&self) -> PartKind {
        self.kind
    }
}

/// A runtime part value.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PartValue<'a> {
    /// A 16-byte UUID.
    Uuid([u8; 16]),
    /// A signed 64-bit integer.
    I64(i64),
    /// Opaque bytes.
    Bytes(&'a [u8]),
}

impl PartValue<'_> {
    pub(crate) fn kind(&self) -> PartKind {
        match self {
            Self::Uuid(_) => PartKind::Uuid,
            Self::I64(_) => PartKind::I64,
            Self::Bytes(_) => PartKind::Bytes,
        }
    }
}

/// The ID of the record a value is bound to, tagged with its kind.
///
/// A record never partitions a blind index. The
/// kind is part of the binding, so the same number as an `i64` and as bytes
/// binds different records.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum RecordId<'a> {
    /// A UUID, such as a client-generated version 7 UUID.
    Uuid([u8; 16]),
    /// A signed 64-bit integer.
    I64(i64),
    /// Opaque bytes.
    Bytes(&'a [u8]),
}

impl<'a> RecordId<'a> {
    /// Creates a record ID from opaque bytes.
    #[must_use]
    pub const fn from_bytes(bytes: &'a [u8]) -> Self {
        Self::Bytes(bytes)
    }

    /// Creates a record ID from any [`PartType`], such as an application's own
    /// ID newtype, with that type's kind and value.
    #[must_use]
    pub fn of<T: PartType + ?Sized>(id: &'a T) -> Self {
        match id.part_value() {
            PartValue::Uuid(uuid) => Self::Uuid(uuid),
            PartValue::I64(value) => Self::I64(value),
            PartValue::Bytes(bytes) => Self::Bytes(bytes),
        }
    }
}

impl From<[u8; 16]> for RecordId<'_> {
    fn from(uuid: [u8; 16]) -> Self {
        Self::Uuid(uuid)
    }
}

#[cfg(feature = "uuid")]
impl From<uuid::Uuid> for RecordId<'_> {
    fn from(uuid: uuid::Uuid) -> Self {
        Self::Uuid(*uuid.as_bytes())
    }
}

impl From<i64> for RecordId<'_> {
    fn from(value: i64) -> Self {
        Self::I64(value)
    }
}

#[cfg(feature = "migrate")]
impl<'a> RecordId<'a> {
    // Records share the part value encoding, kind codes included.
    pub(crate) const fn part_value(self) -> PartValue<'a> {
        match self {
            Self::Uuid(uuid) => PartValue::Uuid(uuid),
            Self::I64(value) => PartValue::I64(value),
            Self::Bytes(bytes) => PartValue::Bytes(bytes),
        }
    }
}

// The part a record is bound as: the nil part ID, which no declared part may
// use, so it always sorts first. See ../docs/wire-format.md#binding.
const fn record_part(kind: PartKind) -> PartSpec {
    PartSpec::from_bytes([0; 16], kind)
}

/// The persistent declaration of a binding: its declared parts and, when it
/// binds a record, the record's kind.
#[derive(Clone, Copy, Debug)]
pub(crate) struct BindingDeclaration<'a> {
    parts: &'a [PartSpec],
    record: Option<PartKind>,
}

impl<'a> BindingDeclaration<'a> {
    pub(crate) const fn new(parts: &'a [PartSpec], record: Option<PartKind>) -> Self {
        Self { parts, record }
    }

    /// Checks the declaration's own invariants: unique, non-nil part IDs.
    ///
    /// Without parts or a record, the declaration is empty: the seal binds
    /// its seal ID alone.
    pub(crate) fn validate(&self) -> Result<(), Error> {
        let mut ids: Vec<_> = self.parts.iter().map(|spec| spec.id).collect();
        ids.sort_unstable();
        let duplicate = ids.windows(2).any(|pair| pair[0] == pair[1]);

        if ids.contains(&[0; 16]) || duplicate {
            return Err(Error::InvalidBinding);
        }

        Ok(())
    }

    /// Every part of the declaration, the record's included.
    fn specs(&self) -> Vec<PartSpec> {
        self.record
            .map(record_part)
            .into_iter()
            .chain(self.parts.iter().copied())
            .collect()
    }

    /// Fingerprints the declaration; part order does not matter.
    pub(crate) fn fingerprint(&self) -> [u8; 8] {
        encoding::fingerprint(&self.specs())
    }
}

/// A binding resolved for the cryptographic core, or its blind-index restriction.
///
/// The encoded bytes are the domain separator that encryption mixes into key
/// derivation and AAD, and that a blind index mixes into its MAC input. The
/// binding fingerprint is recorded in the envelope and checked by readers. The
/// domain starts with the 16 bytes of an identity, a seal ID, which it does not
/// interpret; choosing keys is the typed layer's.
#[derive(Clone, Debug)]
pub(crate) struct BindingDomain {
    encoded: Vec<u8>,
    fingerprint: [u8; 8],
}

impl BindingDomain {
    /// Encodes a seal's declared parts, in any order, with their values, and
    /// its record if the declaration binds one.
    ///
    /// Without parts or a record, the declaration is empty and the seal binds
    /// its seal ID alone.
    ///
    /// `values` follows the order of `declaration`'s parts.
    pub(crate) fn scoped(
        id: &[u8; 16],
        declaration: BindingDeclaration<'_>,
        values: &[PartValue<'_>],
        record: Option<PartValue<'_>>,
    ) -> Result<Self, Error> {
        declaration.validate()?;
        check_values(declaration.parts, values)?;
        let record = match (declaration.record, record) {
            (Some(kind), Some(record)) if record.kind() == kind => {
                Some((record_part(kind), record))
            }
            (None, None) => None,
            _ => return Err(Error::InvalidBinding),
        };

        let parts: Vec<_> = record
            .iter()
            .map(|(spec, value)| (spec, value))
            .chain(declaration.parts.iter().zip(values))
            .collect();
        Ok(Self {
            encoded: encoding::encode(id, parts)?,
            fingerprint: declaration.fingerprint(),
        })
    }

    /// Encodes the binding of seal `id`, which binds `L` and record `R`, under
    /// `L`'s values, in list order, and the record if `R` is one.
    pub(crate) fn bound<L: BoundList, R: RecordIdType>(
        id: &[u8; 16],
        values: &[PartValue<'_>],
        record: Option<PartValue<'_>>,
    ) -> Result<Self, Error> {
        Self::scoped(
            id,
            BindingDeclaration::new(L::PARTS, R::RECORD),
            values,
            record,
        )
    }

    /// Encodes the blind-index domain of seal `id` under partition `P`'s
    /// values: every part of `P`, without a record, or the empty binding
    /// without parts.
    // See ../docs/wire-format.md#index-binding.
    pub(crate) fn index<P: BoundList>(
        id: &[u8; 16],
        values: &[PartValue<'_>],
    ) -> Result<Self, Error> {
        Self::scoped(id, BindingDeclaration::new(P::PARTS, None), values, None)
    }

    /// Encodes the binding of seal `id` under the older declaration of `Old` and
    /// record `OldRecord`, taking each of `Old`'s values from `values`, of
    /// `parts`, by part ID, and binding `record` when `OldRecord` is one.
    ///
    /// A part of `Old` that `parts` lacks, or holds with another kind, and a
    /// record `OldRecord` binds but `record` lacks, are [`Error::InvalidBinding`].
    #[cfg(feature = "migrate")]
    pub(crate) fn projected<Old: BoundList, OldRecord: RecordIdType>(
        id: &[u8; 16],
        parts: &[PartSpec],
        values: &[PartValue<'_>],
        record: Option<PartValue<'_>>,
    ) -> Result<Self, Error> {
        let values = project(Old::PARTS, parts, values)?;
        let record = if OldRecord::RECORD.is_some() {
            record
        } else {
            None
        };

        Self::bound::<Old, OldRecord>(id, &values, record)
    }

    /// The binding fingerprint the envelope header carries.
    pub(crate) fn fingerprint(&self) -> [u8; 8] {
        self.fingerprint
    }

    pub(crate) fn as_bytes(&self) -> &[u8] {
        &self.encoded
    }
}

/// Creates a [`PartId`](crate::PartId) from a UUID literal.
#[macro_export]
macro_rules! part_id {
    ($value:literal) => {{
        const ID: $crate::PartId =
            $crate::PartId::from_bytes($crate::__private::uuid::uuid!($value).into_bytes());
        ID
    }};
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::seal_id;

    const SEAL: [u8; 16] = *seal_id!("12345678-1234-4234-8234-1234567890ab").as_bytes();

    #[test]
    fn the_empty_binding_is_the_seal_id_without_parts() {
        let domain = scoped(&[], None, &[], None).unwrap();

        // docs/wire-format.md#binding
        assert_eq!(
            hex::encode(domain.as_bytes()),
            "123456781234423482341234567890ab0000"
        );
    }

    const TENANT: PartSpec = PartSpec::from_bytes([0x11; 16], PartKind::Uuid);
    const SEQUENCE: PartSpec = PartSpec::from_bytes([0xaa; 16], PartKind::I64);

    #[test]
    fn scoped_binding_sorts_and_frames_parts() {
        // Declared out of order: the encoding sorts parts by part ID.
        let domain = BindingDomain::scoped(
            &SEAL,
            BindingDeclaration::new(&[SEQUENCE, TENANT], None),
            &[PartValue::I64(-2), PartValue::Uuid([0x33; 16])],
            None,
        )
        .unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            concat!(
                "123456781234423482341234567890ab",
                "0002",
                "11111111111111111111111111111111",
                "01",
                "00000010",
                "33333333333333333333333333333333",
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "02",
                "00000008",
                "fffffffffffffffe",
            )
        );
    }

    #[test]
    fn a_record_is_a_part_with_the_nil_id_that_sorts_first() {
        let domain = BindingDomain::scoped(
            &SEAL,
            BindingDeclaration::new(&[TENANT], Some(PartKind::Bytes)),
            &[PartValue::Uuid([0x33; 16])],
            Some(PartValue::Bytes(b"row-7")),
        )
        .unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            concat!(
                "123456781234423482341234567890ab",
                "0002",
                "00000000000000000000000000000000",
                "03",
                "00000005",
                "726f772d37",
                "11111111111111111111111111111111",
                "01",
                "00000010",
                "33333333333333333333333333333333",
            )
        );
    }

    const LEFT: PartSpec = PartSpec::from_bytes([0x21; 16], PartKind::Bytes);
    const RIGHT: PartSpec = PartSpec::from_bytes([0x22; 16], PartKind::Bytes);

    fn bytes_of(
        parts: &[PartSpec],
        values: &[PartValue<'_>],
        record: Option<PartValue<'_>>,
    ) -> Vec<u8> {
        BindingDomain::scoped(
            &SEAL,
            BindingDeclaration::new(parts, record.map(|record| record.kind())),
            values,
            record,
        )
        .unwrap()
        .as_bytes()
        .to_vec()
    }

    #[test]
    fn part_boundaries_are_unambiguous() {
        assert_ne!(
            bytes_of(
                &[LEFT, RIGHT],
                &[PartValue::Bytes(b"ab"), PartValue::Bytes(b"c")],
                None
            ),
            bytes_of(
                &[LEFT, RIGHT],
                &[PartValue::Bytes(b"a"), PartValue::Bytes(b"bc")],
                None
            ),
        );
    }

    #[test]
    fn an_empty_record_differs_from_no_record() {
        assert_ne!(
            bytes_of(&[LEFT], &[PartValue::Bytes(b"x")], None),
            bytes_of(
                &[LEFT],
                &[PartValue::Bytes(b"x")],
                Some(PartValue::Bytes(b""))
            ),
        );
    }

    #[test]
    fn values_of_different_kinds_never_collide() {
        let as_bytes = PartSpec::from_bytes([0x21; 16], PartKind::Bytes);
        let as_i64 = PartSpec::from_bytes([0x21; 16], PartKind::I64);
        let as_uuid = PartSpec::from_bytes([0x21; 16], PartKind::Uuid);

        assert_ne!(
            bytes_of(&[as_bytes], &[PartValue::Bytes(&7_i64.to_be_bytes())], None),
            bytes_of(&[as_i64], &[PartValue::I64(7)], None),
        );
        assert_ne!(
            bytes_of(&[as_bytes], &[PartValue::Bytes(&[0x33; 16])], None),
            bytes_of(&[as_uuid], &[PartValue::Uuid([0x33; 16])], None),
        );
        assert_ne!(
            bytes_of(
                &[LEFT],
                &[PartValue::Bytes(b"x")],
                Some(PartValue::Bytes(&7_i64.to_be_bytes()))
            ),
            bytes_of(&[LEFT], &[PartValue::Bytes(b"x")], Some(PartValue::I64(7))),
        );
    }

    fn scoped(
        parts: &[PartSpec],
        record: Option<PartKind>,
        values: &[PartValue<'_>],
        record_value: Option<PartValue<'_>>,
    ) -> Result<BindingDomain, Error> {
        BindingDomain::scoped(
            &SEAL,
            BindingDeclaration::new(parts, record),
            values,
            record_value,
        )
    }

    #[test]
    fn invalid_bindings_are_rejected() {
        let uuid = PartValue::Uuid([0x33; 16]);
        let nil = PartSpec::from_bytes([0; 16], PartKind::Uuid);
        let cases: [(&str, Result<BindingDomain, Error>); 9] = [
            ("value without a part", scoped(&[], None, &[uuid], None)),
            (
                "duplicate part ID",
                scoped(&[TENANT, TENANT], None, &[uuid, uuid], None),
            ),
            ("nil part ID", scoped(&[nil], None, &[uuid], None)),
            ("missing value", scoped(&[TENANT], None, &[], None)),
            ("extra value", scoped(&[TENANT], None, &[uuid, uuid], None)),
            (
                "kind mismatch",
                scoped(&[TENANT], None, &[PartValue::I64(1)], None),
            ),
            (
                "missing record",
                scoped(&[TENANT], Some(PartKind::Uuid), &[uuid], None),
            ),
            (
                "record of another kind",
                scoped(&[TENANT], Some(PartKind::I64), &[uuid], Some(uuid)),
            ),
            (
                "unexpected record",
                scoped(&[TENANT], None, &[uuid], Some(uuid)),
            ),
        ];

        for (case, result) in cases {
            assert_eq!(result.unwrap_err(), Error::InvalidBinding, "{case}");
        }
    }

    #[test]
    fn declaration_fingerprint_is_truncated_sha256_of_the_sorted_parts() {
        // Independently computed with shasum over the documented declaration bytes.
        assert_eq!(
            BindingDeclaration::new(&[SEQUENCE, TENANT], None).fingerprint(),
            hex_array("ccaf295688d461dc"),
        );
        assert_eq!(
            BindingDeclaration::new(&[TENANT], Some(PartKind::I64)).fingerprint(),
            hex_array("0e4e1152693fffd1"),
        );
    }

    #[test]
    fn declaration_fingerprint_ignores_part_order_but_not_kinds() {
        let fingerprint = BindingDeclaration::new(&[SEQUENCE, TENANT], None).fingerprint();
        let tenant_bytes = PartSpec::from_bytes([0x11; 16], PartKind::Bytes);

        assert_eq!(
            BindingDeclaration::new(&[TENANT, SEQUENCE], None).fingerprint(),
            fingerprint
        );
        assert_ne!(
            BindingDeclaration::new(&[SEQUENCE, tenant_bytes], None).fingerprint(),
            fingerprint
        );
        assert_ne!(
            BindingDeclaration::new(&[SEQUENCE, TENANT], Some(PartKind::I64)).fingerprint(),
            fingerprint
        );
        // The record's kind is declared, like any part's.
        assert_ne!(
            BindingDeclaration::new(&[], Some(PartKind::I64)).fingerprint(),
            BindingDeclaration::new(&[], Some(PartKind::Bytes)).fingerprint(),
        );
    }

    #[test]
    fn every_domain_carries_its_declaration_fingerprint() {
        let declaration = BindingDeclaration::new(&[TENANT], None);
        let domain = scoped(&[TENANT], None, &[PartValue::Uuid([0x33; 16])], None).unwrap();

        assert_eq!(domain.fingerprint(), declaration.fingerprint());
        // Independently computed with shasum over the documented empty declaration.
        assert_eq!(
            scoped(&[], None, &[], None).unwrap().fingerprint(),
            hex_array("65640fc8333534b9")
        );
    }

    fn hex_array(value: &str) -> [u8; 8] {
        hex::decode(value).unwrap().try_into().unwrap()
    }

    #[test]
    fn a_record_alone_binds_the_record_without_parts() {
        let domain = scoped(&[], Some(PartKind::I64), &[], Some(PartValue::I64(1))).unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            concat!(
                "123456781234423482341234567890ab",
                "0001",
                "00000000000000000000000000000000",
                "02",
                "00000008",
                "0000000000000001",
            )
        );
        // Independently computed with shasum over the documented declaration bytes.
        assert_eq!(domain.fingerprint(), hex_array("76081b730530f822"));
    }

    const ORG: PartSpec = PartSpec::from_bytes([0x11; 16], PartKind::Uuid);
    const WORKSPACE: PartSpec = PartSpec::from_bytes([0x22; 16], PartKind::Bytes);
    const WS1: [PartValue<'static>; 2] = [PartValue::Uuid([0x33; 16]), PartValue::Bytes(b"ws-1")];

    #[test]
    fn a_two_part_binding_encodes_the_documented_vector() {
        // docs/wire-format.md#provisional-bound-vectors
        let domain = scoped(&[ORG, WORKSPACE], None, &WS1, None).unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            "123456781234423482341234567890ab00021111111111111111111111111111111101000000103333333333333333333333333333333322222222222222222222222222222222030000000477732d31"
        );
        assert_eq!(domain.fingerprint(), hex_array("0d940ea58b80d8bd"));
    }

    #[test]
    fn a_two_part_binding_binds_the_record_first_documented_vector() {
        let domain = scoped(
            &[ORG, WORKSPACE],
            Some(PartKind::I64),
            &WS1,
            Some(PartValue::I64(7)),
        )
        .unwrap();

        assert_eq!(
            hex::encode(domain.as_bytes()),
            "123456781234423482341234567890ab0003000000000000000000000000000000000200000008000000000000000711111111111111111111111111111111010000001033333333333333333333333333333333222222222222222222222222222222220300000004 77732d31".replace(' ', "")
        );
        assert_eq!(domain.fingerprint(), hex_array("27689c2e3de5d291"));
    }

    #[test]
    fn a_projection_takes_values_by_part_id() {
        let projected = project(&[WORKSPACE], &[ORG, WORKSPACE], &WS1).unwrap();

        assert!(matches!(projected.as_slice(), [PartValue::Bytes(b"ws-1")]));
        assert!(project(&[], &[ORG, WORKSPACE], &WS1).unwrap().is_empty());
        assert_eq!(
            project(&[SEQUENCE], &[ORG, WORKSPACE], &WS1).unwrap_err(),
            Error::InvalidBinding
        );
    }

    #[test]
    fn a_view_matches_parts_by_id_and_kind() {
        let org_as_bytes = PartSpec::from_bytes([0x11; 16], PartKind::Bytes);

        assert!(is_view(&[], &[ORG, WORKSPACE]));
        assert!(is_view(&[ORG], &[ORG, WORKSPACE]));
        assert!(is_view(&[ORG, WORKSPACE], &[ORG, WORKSPACE]));
        assert!(!is_view(&[ORG], &[WORKSPACE]));
        assert!(!is_view(&[org_as_bytes], &[ORG, WORKSPACE]));
    }
}
