use crate::{Binding, Codec, IndexList, Padding, SealId};

/// Declares how values are sealed: their identity, value type, codec,
/// padding, binding, and blind indexes.
///
/// A seal is a marker type, separate from the application's value type. The
/// value type (`String`, `Address`, `Secret<String>`) says how it encodes; the
/// seal gives its values an identity. One value type can back several seals, such
/// as `HomeAddress` and `BillingAddress` over one `Address`, and each seal has
/// its own ID so their sealed values cannot be swapped. A seal is not tied to
/// storage: its values may be database columns, messages, or whole responses.
///
/// Every sealed value is bound at runtime to its seal ID, to the values of the
/// seal's [`Binding`] (such as a tenant), and, when [`Self::RECORD`] is set, to
/// a record ID. Opening it as another seal, or under other binding values or
/// another record, fails authentication. The binding arguments of each call are
/// typed by the seal; see [`Args`](crate::Args).
///
/// Generate a unique ID for each seal, keep it stable across Rust and database
/// renames, and never reuse it for a different seal. Changing the ID makes
/// existing values fail authentication. Declaring the same ID on several types
/// deliberately makes them the same seal.
///
/// The value type, codec representation, seal ID, and binding declaration define
/// persistent schema. The envelope does not store a codec identifier, so
/// incompatible changes require an explicit data migration. Padding is write
/// policy instead: the envelope records whether a value is padded. See
/// [`crate::schema`] and [`crate::testing`] for CI checks of the codec and IDs;
/// an envelope written with another binding declaration reports
/// [`Error::BindingMismatch`](crate::Error::BindingMismatch) when opened.
///
/// For blind indexes, the seal domain-separates derivation; it does not
/// authenticate the stored index representation. Compare decrypted candidate
/// plaintext for lookup, and recompute indexes separately when stored-index
/// consistency is required.
///
/// # Examples
///
/// ```
/// use cryptbox::{Seal, SealId, FieldOnly, Padding, Plaintext};
///
/// /// Primary contact address.
/// pub struct UserEmail;
///
/// impl Seal for UserEmail {
///     const ID: SealId = cryptbox::seal_id!("ca274e85-63c4-4f7d-a255-2dfecbfe5e25");
///     const PADDING: Padding = Padding::NONE;
///     const RECORD: bool = false;
///     type Value = String;
///     type Codec = <String as Plaintext>::Codec;
///     type Binding = FieldOnly;
///     type Indexes = ();
/// }
/// ```
///
/// With the `derive` feature, `#[derive(Seal)]` writes exactly this impl from
/// `#[cryptbox(id = "ca274e85-63c4-4f7d-a255-2dfecbfe5e25", value = String)]`.
/// Add `binding = Tenant`, `record`, or `indexes(EmailLookup)` to set
/// [`Self::Binding`], [`Self::RECORD`], or [`Self::Indexes`].
///
/// A value type without a [`Plaintext`](crate::Plaintext) implementation has no
/// default codec; implement `Plaintext` for it or name an explicit codec:
///
/// ```compile_fail,E0277
/// use cryptbox::{Seal, SealId, FieldOnly, Padding, Plaintext};
///
/// struct Address {
///     city: String,
/// }
///
/// struct HomeAddress;
///
/// impl Seal for HomeAddress {
///     const ID: SealId = cryptbox::seal_id!("0b6f3c2a-8e41-4d57-a9c3-5e1f2d7b8a64");
///     const PADDING: Padding = Padding::NONE;
///     const RECORD: bool = false;
///     type Value = Address;
///     type Codec = <Address as Plaintext>::Codec;
///     type Binding = FieldOnly;
///     type Indexes = ();
/// }
/// ```
///
/// See the [custom-field example] and [ownership reference].
///
#[doc = concat!(
    "[custom-field example]: ", env!("CARGO_PKG_REPOSITORY"), "/blob/main/examples/custom_field/README.md\n",
    "[ownership reference]: ", env!("CARGO_PKG_REPOSITORY"), "/blob/main/docs/ownership.md",
)]
pub trait Seal: 'static {
    /// The stable identifier, independent of Rust and database names.
    const ID: SealId;

    /// The padding policy applied to new values between the codec and encryption.
    ///
    /// This describes how values are written, not how they are read: the
    /// envelope records whether its payload is padded. Changing the policy keeps
    /// stored values readable, and resealing rewrites them with it; see
    /// [`Padding`].
    const PADDING: Padding;

    /// Whether every value is also bound to the ID of its record.
    ///
    /// A record-bound value cannot be copied to another record of the same
    /// seal. The record is always bound only: it never scopes keys or blind
    /// indexes. Record IDs are generated by the client, before the value is
    /// sealed. Changing this flag is a migration.
    const RECORD: bool;

    /// The plaintext application type of this seal's values.
    type Value;

    /// The codec used before encryption and after decryption.
    ///
    /// Its byte representation must remain compatible with stored values.
    /// Use `<Self::Value as Plaintext>::Codec` for the value type's default codec.
    type Codec: Codec<Self::Value>;

    /// The declared scope every value is bound to, such as a tenant.
    ///
    /// [`FieldOnly`](crate::FieldOnly) binds values to the seal ID alone. The
    /// binding's declaration is persistent schema; its values are supplied at each
    /// call. See [`Binding`].
    type Binding: Binding;

    /// The blind indexes declared over this seal, as a tuple of
    /// [`BlindIndexSpec`](crate::BlindIndexSpec)s, or `()` for none.
    ///
    /// Declaring them lets storage helpers reject a seal whose blind indexes
    /// they would not write, such as the automatic column
    /// [`Plain`](crate::Plain). See [`IndexList`].
    type Indexes: IndexList<Self>;
}
